name: Actualizar Fecha Firebase

on:
  push:
    branches:
      - main
      - master
    # MAGIA ACTUALIZADA: Ahora vigila JSON y todos los formatos de imagen comunes
    paths:
      - '**.json'
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.webp'
      - '**.svg'

jobs:
  update-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Ejecutar script de actualización de fecha
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node update_firebase_date.js
